In [1]:
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "2"

In [2]:
import numpy as np
import pandas as pd

In [3]:
# 표제부 전처리 진행
# 파일 경로 지정
file_path = 'files/dataset/원본데이터/표제부데이터셋/표제부.txt'

# 헤더 리스트 생성
headers = [
    "관리건축물대장PK", "대장구분코드", "대장구분코드명", "대장종류코드", "대장종류코드명",
    "대지위치", "도로명대지위치", "건물명", "시군구코드", "법정동코드", "대지구분코드", "번", "지",
    "특수지명", "블록", "로트", "외필지수", "새주소도로코드", "새주소법정동코드", "새주소지상지하코드",
    "새주소본번", "새주소부번", "동명칭", "주부속구분코드", "주부속구분코드명", "대지면적(㎡)",
    "건축면적(㎡)", "건폐율(%)", "연면적(㎡)", "용적률산정연면적(㎡)", "용적률(%)", "구조코드",
    "구조코드명", "기타구조", "주용도코드", "주용도코드명", "기타용도", "지붕코드", "지붕코드명",
    "기타지붕", "세대수(세대)", "가구수(가구)", "높이(m)", "지상층수", "지하층수", "승용승강기수",
    "비상용승강기수", "부속건축물수", "부속건축물면적(㎡)", "총동연면적(㎡)", "옥내기계식대수(대)",
    "옥내기계식면적(㎡)", "옥외기계식대수(대)", "옥외기계식면적(㎡)", "옥내자주식대수(대)",
    "옥내자주식면적(㎡)", "옥외자주식대수(대)", "옥외자주식면적(㎡)", "허가일", "착공일", "사용승인일",
    "허가번호년", "허가번호기관코드", "허가번호기관코드명", "허가번호구분코드", "허가번호구분코드명",
    "호수(호)", "에너지효율등급", "에너지절감율", "EPI점수", "친환경건축물등급", "친환경건축물인증점수",
    "지능형건축물등급", "지능형건축물인증점수", "생성일자", "내진설계적용여부", "내진능력"
]

field_mapping = {
    '주용도코드명': 'main_purps_cd_nm',
    '세대수(세대)': 'hhld_cnt',
    '생성일자': 'crtn_day',
    '대지위치': 'plat_plc',
    '시군구코드': 'sigungu_cd',
    '법정동코드': 'bjdong_cd',
    '대장종류코드': 'regstr_kind_cd',
    '대장종류코드명': 'regstr_kind_cd_nm',
    '도로명대지위치': 'new_plat_plc',
    '건물명': 'bld_nm',
    '대지면적(㎡)': 'plat_area',
    '건축면적(㎡)': 'arch_area',
    '건폐율(%)': 'bc_rat',
    '연면적(㎡)': 'tot_area',
    '용적률(%)': 'vl_rat',
}


# pnu 코드를 만드는 함수
def create_pnu(row):
    # 대장구분코드 조건에 따라 변환
    if row['대지구분코드'] == '0':
        plat_code = '1'
    elif row['대지구분코드'] == '1':
        plat_code = '2'
    else:
        return None

    # '번'과 '지'를 문자열로 강제 변환하고 zfill로 패딩 추가
    bun = str(int(row['번'])).zfill(4)
    ji = str(int(row['지'])).zfill(4)
    return f"{row['시군구코드']}{row['법정동코드']}{plat_code}{bun}{ji}"


# 데이터프레임으로 읽어오기
df = pd.read_csv(file_path, delimiter='|', encoding='cp949', names=headers,
                 dtype={'법정동코드': str, '시군구코드': str, '대지구분코드': str, '번': str, '지': str})

df

/tmp/ipykernel_2693394/2219236771.py:59: DtypeWarning: Columns (14,15,31,34,58,59,60,61,62,67,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, delimiter='|', encoding='cp949', names=headers,

,관리건축물대장PK,대장구분코드,대장구분코드명,대장종류코드,대장종류코드명,대지위치,도로명대지위치,건물명,시군구코드,법정동코드,...,에너지효율등급,에너지절감율,EPI점수,친환경건축물등급,친환경건축물인증점수,지능형건축물등급,지능형건축물인증점수,생성일자,내진설계적용여부,내진능력
0,51150-16236,2,집합,3,표제부,강원특별자치도 강릉시 송정동 1061번지,강원특별자치도 강릉시 해안로 93-8,경포대신도브래뉴로얄카운티아파트,51150,11400,...,NaN,0.0,0,NaN,0,NaN,0,20100417,NaN,NaN
1,51150-16238,2,집합,3,표제부,강원특별자치도 강릉시 송정동 1061번지,강원특별자치도 강릉시 해안로 93-8,경포대신도브래뉴로얄카운티아파트,51150,11400,...,NaN,0.0,0,NaN,0,NaN,0,20100417,NaN,NaN
2,51150-16239,2,집합,3,표제부,강원특별자치도 강릉시 송정동 1061번지,강원특별자치도 강릉시 해안로 93-8,경포대신도브래뉴로얄카운티아파트,51150,11400,...,NaN,0.0,0,NaN,0,NaN,0,20100417,NaN,NaN
3,48840-8995,1,일반,2,일반건축물,경상남도 남해군 남면 죽전리 384-5번지,경상남도 남해군 남면 남서대로 785-12,남면복지회관,48840,35029,...,NaN,0.0,0,NaN,0,NaN,0,20100625,NaN,NaN
4,30200-3324,2,집합,3,표제부,대전광역시 유성구 용계동 271-2번지,대전광역시 유성구 용계로 101-18,NaN,30200,10400,...,NaN,0.0,0,NaN,0,NaN,0,20100417,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8000898,44270-26009,1,일반,2,일반건축물,충청남도 당진시 대호지면 조금리 산 30-1번지,,NaN,44270,33021,...,NaN,0.0,0,NaN,0,NaN,0,20220307,0.0,NaN
8000899,44270-26064,1,일반,2,일반건축물,충청남도 당진시 대호지면 사성리 50-1번지,,NaN,44270,33022,...,NaN,0.0,0,NaN,0,NaN,0,20220307,0.0,NaN
8000900,44270-51347,1,일반,2,일반건축물,충청남도 당진시 송산면 동곡리 18-12번지,,NaN,44270,39032,...,NaN,0.0,0,NaN,0,NaN,0,20220307,0.0,NaN
8000901,44270-51433,1,일반,2,일반건축물,충청남도 당진시 송산면 동곡리 156-26번지,충청남도 당진시 송산면 동곡로 84-67,소매점,44270,39032,...,NaN,0.0,0,NaN,0,NaN,0,20220307,0.0,NaN
8000902,44270-46230,1,일반,2,일반건축물,충청남도 당진시 송악읍 중흥리 339-4번지,,NaN,44270,25334,...,NaN,0.0,0,NaN,0,NaN,0,20220307,0.0,NaN

In [4]:
# 'address' 열에서 '번지' 문자열 제거
df['대지위치'] = df['대지위치'].str.replace('번지', '', regex=False)

# '시군구코드','법정동코드','대장구분코드','번', '지' 컬럼이 null인 행을 제거
df.dropna(subset=['시군구코드', '법정동코드', '대지구분코드', '번', '지','주용도코드명','세대수(세대)','가구수(가구)','호수(호)'], inplace=True)

df

,관리건축물대장PK,대장구분코드,대장구분코드명,대장종류코드,대장종류코드명,대지위치,도로명대지위치,건물명,시군구코드,법정동코드,...,에너지효율등급,에너지절감율,EPI점수,친환경건축물등급,친환경건축물인증점수,지능형건축물등급,지능형건축물인증점수,생성일자,내진설계적용여부,내진능력
0,51150-16236,2,집합,3,표제부,강원특별자치도 강릉시 송정동 1061,강원특별자치도 강릉시 해안로 93-8,경포대신도브래뉴로얄카운티아파트,51150,11400,...,NaN,0.0,0,NaN,0,NaN,0,20100417,NaN,NaN
1,51150-16238,2,집합,3,표제부,강원특별자치도 강릉시 송정동 1061,강원특별자치도 강릉시 해안로 93-8,경포대신도브래뉴로얄카운티아파트,51150,11400,...,NaN,0.0,0,NaN,0,NaN,0,20100417,NaN,NaN
2,51150-16239,2,집합,3,표제부,강원특별자치도 강릉시 송정동 1061,강원특별자치도 강릉시 해안로 93-8,경포대신도브래뉴로얄카운티아파트,51150,11400,...,NaN,0.0,0,NaN,0,NaN,0,20100417,NaN,NaN
3,48840-8995,1,일반,2,일반건축물,경상남도 남해군 남면 죽전리 384-5,경상남도 남해군 남면 남서대로 785-12,남면복지회관,48840,35029,...,NaN,0.0,0,NaN,0,NaN,0,20100625,NaN,NaN
4,30200-3324,2,집합,3,표제부,대전광역시 유성구 용계동 271-2,대전광역시 유성구 용계로 101-18,NaN,30200,10400,...,NaN,0.0,0,NaN,0,NaN,0,20100417,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8000898,44270-26009,1,일반,2,일반건축물,충청남도 당진시 대호지면 조금리 산 30-1,,NaN,44270,33021,...,NaN,0.0,0,NaN,0,NaN,0,20220307,0.0,NaN
8000899,44270-26064,1,일반,2,일반건축물,충청남도 당진시 대호지면 사성리 50-1,,NaN,44270,33022,...,NaN,0.0,0,NaN,0,NaN,0,20220307,0.0,NaN
8000900,44270-51347,1,일반,2,일반건축물,충청남도 당진시 송산면 동곡리 18-12,,NaN,44270,39032,...,NaN,0.0,0,NaN,0,NaN,0,20220307,0.0,NaN
8000901,44270-51433,1,일반,2,일반건축물,충청남도 당진시 송산면 동곡리 156-26,충청남도 당진시 송산면 동곡로 84-67,소매점,44270,39032,...,NaN,0.0,0,NaN,0,NaN,0,20220307,0.0,NaN
8000902,44270-46230,1,일반,2,일반건축물,충청남도 당진시 송악읍 중흥리 339-4,,NaN,44270,25334,...,NaN,0.0,0,NaN,0,NaN,0,20220307,0.0,NaN

In [5]:
# 새로운 pnu 코드 컬럼 추가
df['pnu_code'] = df.apply(create_pnu, axis=1)

# 일반, 산이 아닌경우 None을 넣어 제거
df.dropna(subset=['pnu_code'], inplace=True)

# 세대수가 0인 경우, 가구수 컬럼으로 먼저 대체
df['세대수(세대)'] = np.where(df['세대수(세대)'] == 0, df['가구수(가구)'], df['세대수(세대)'])

# 위에서 계산한 결과가 여전히 0이면, 호수 컬럼으로 대체
df['세대수(세대)'] = np.where(df['세대수(세대)'] == 0, df['호수(호)'], df['세대수(세대)'])

# 총 주차대수 컬럼 생성 및 계산
df['tot_pkng_cnt'] = df['옥내기계식대수(대)'] + df['옥외기계식대수(대)'] + df['옥내자주식대수(대)'] + df['옥외자주식대수(대)']

# 데이터프레임 제거 컬럼 선정 후 제거
df.drop(columns=['지붕코드', '지붕코드명', '기타지붕', '가구수(가구)', '비상용승강기수', '부속건축물수', '부속건축물면적(㎡)', '총동연면적(㎡)', '옥내기계식면적(㎡)',
                 '옥외기계식면적(㎡)', '옥내자주식면적(㎡)', '옥외자주식면적(㎡)', '허가번호년', '허가번호기관코드', '허가번호기관코드명', '허가번호구분코드', '허가번호구분코드명',
                 '호수(호)', '에너지효율등급', '에너지절감율', 'EPI점수', '친환경건축물등급', '친환경건축물인증점수', '지능형건축물등급', '지능형건축물인증점수',
                 '대장구분코드', '대장구분코드명', '특수지명', '블록', '로트', '외필지수', '새주소지상지하코드', '주부속구분코드',
                 '용적률산정연면적(㎡)', '구조코드', '기타구조', '주용도코드', '내진능력', '새주소도로코드', '새주소법정동코드', '새주소본번', '새주소부번', '관리건축물대장PK',
                 '대지구분코드', '번', '지', '옥내기계식대수(대)', '옥외기계식대수(대)', '옥내자주식대수(대)', '옥외자주식대수(대)', '기타용도', '허가일', '착공일',
                 '사용승인일'],

# 문자열을 포함하고 있는 열만 확인하여 앞뒤 공백 찍힌거 제거
for column in df.columns:  
    if df[column].dtype == 'object':
        df[column] = df[column].str.strip()

df

,대장종류코드,대장종류코드명,대지위치,도로명대지위치,건물명,시군구코드,법정동코드,동명칭,주부속구분코드명,대지면적(㎡),...,주용도코드명,세대수(세대),높이(m),지상층수,지하층수,승용승강기수,생성일자,내진설계적용여부,pnu_code,tot_pkng_cnt
0,3,표제부,강원특별자치도 강릉시 송정동 1061,강원특별자치도 강릉시 해안로 93-8,경포대신도브래뉴로얄카운티아파트,51150,11400,"경로당,관리사무소",부속건축물,0.0,...,공동주택,0,8.10,2,0,0,20100417,NaN,5115011400110610000,0
1,3,표제부,강원특별자치도 강릉시 송정동 1061,강원특별자치도 강릉시 해안로 93-8,경포대신도브래뉴로얄카운티아파트,51150,11400,가스정압실,부속건축물,0.0,...,공동주택,0,4.90,1,0,0,20100417,NaN,5115011400110610000,0
2,3,표제부,강원특별자치도 강릉시 송정동 1061,강원특별자치도 강릉시 해안로 93-8,경포대신도브래뉴로얄카운티아파트,51150,11400,경비실,부속건축물,0.0,...,공동주택,0,3.97,1,0,0,20100417,NaN,5115011400110610000,0
3,2,일반건축물,경상남도 남해군 남면 죽전리 384-5,경상남도 남해군 남면 남서대로 785-12,남면복지회관,48840,35029,1동,주건축물,0.0,...,제1종근린생활시설,0,8.00,2,1,0,20100625,NaN,4884035029103840005,0
4,3,표제부,대전광역시 유성구 용계동 271-2,대전광역시 유성구 용계로 101-18,NaN,30200,10400,NaN,주건축물,202.0,...,공동주택,2,3.80,1,0,0,20100417,NaN,3020010400102710002,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8000898,2,일반건축물,충청남도 당진시 대호지면 조금리 산 30-1,,NaN,44270,33021,NaN,주건축물,989.0,...,제2종근린생활시설,0,3.00,1,0,0,20220307,0.0,4427033021200300001,0
8000899,2,일반건축물,충청남도 당진시 대호지면 사성리 50-1,,NaN,44270,33022,NaN,주건축물,205.0,...,동물및식물관련시설,0,0.00,1,0,0,20220307,0.0,4427033022100500001,0
8000900,2,일반건축물,충청남도 당진시 송산면 동곡리 18-12,,NaN,44270,39032,NaN,주건축물,0.0,...,동물및식물관련시설,0,0.00,1,0,0,20220307,0.0,4427039032100180012,0
8000901,2,일반건축물,충청남도 당진시 송산면 동곡리 156-26,충청남도 당진시 송산면 동곡로 84-67,소매점,44270,39032,1동,주건축물,990.0,...,제1종근린생활시설,0,0.00,1,0,0,20220307,0.0,4427039032101560026,0
8000902,2,일반건축물,충청남도 당진시 송악읍 중흥리 339-4,,NaN,44270,25334,NaN,주건축물,0.0,...,공장,0,0.00,1,0,0,20220307,0.0,4427025334103390004,0

In [6]:
# `pnu_code`의 각 값에 대해 카운트를 계산
counts = df['pnu_code'].value_counts()

# 한 번만 등장하는 `pnu_code` 값을 가진 행을 필터링
unique_pnu_codes = counts[counts == 1].index

# 유일한 `pnu_code` 값을 가진 행만 선택
unique_rows = df[df['pnu_code'].isin(unique_pnu_codes)].copy()
unique_rows.loc[:, 'main_bld_cnt'] = 1

result_df = unique_rows[['pnu_code','대지면적(㎡)','건축면적(㎡)','건폐율(%)','연면적(㎡)','용적률(%)','주용도코드명','세대수(세대)',
                        'tot_pkng_cnt','대지위치','시군구코드','법정동코드','도로명대지위치',
                       '건물명','생성일자','대장종류코드','대장종류코드명','main_bld_cnt']].copy()

# 날짜 열을 datetime 형식으로 변환
result_df['생성일자'] = pd.to_datetime(result_df['생성일자'], format='%Y%m%d')

# 데이터프레임 컬럼명 영문으로 변경
result_df.rename(columns=field_mapping, inplace=True)

result_df

,pnu_code,plat_area,arch_area,bc_rat,tot_area,vl_rat,main_purps_cd_nm,hhld_cnt,tot_pkng_cnt,plat_plc,sigungu_cd,bjdong_cd,new_plat_plc,bld_nm,crtn_day,regstr_kind_cd,regstr_kind_cd_nm,main_bld_cnt
4,3020010400102710002,202.0,40.04,19.82,38.40,19.01,공동주택,2,2,대전광역시 유성구 용계동 271-2,30200,10400,대전광역시 유성구 용계로 101-18,NaN,2010-04-17,3,표제부,1
5,3020010400101650014,719.0,141.48,19.68,546.24,75.97,공동주택,19,13,대전광역시 유성구 용계동 165-14,30200,10400,대전광역시 유성구 용계로94번길 136-7,NaN,2010-04-17,3,표제부,1
7,2729011100108770001,191.8,112.83,58.83,193.80,101.04,공동주택,2,0,대구광역시 달서구 용산동 877-1,27290,11100,대구광역시 달서구 와룡로51길 64-20,NaN,2010-04-17,3,표제부,1
8,2717010200127150000,69.4,50.95,73.41,152.85,220.24,공동주택,2,0,대구광역시 서구 비산동 2715,27170,10200,대구광역시 서구 북비산로74길 35-2,NaN,2010-04-17,3,표제부,1
14,2811014700104310001,0.0,0.00,0.00,69.09,0.00,단독주택,0,0,인천광역시 중구 운서동 431-1,28110,14700,,NaN,2009-03-17,2,일반건축물,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8000898,4427033021200300001,989.0,142.88,14.45,142.88,14.45,제2종근린생활시설,0,0,충청남도 당진시 대호지면 조금리 산 30-1,44270,33021,,NaN,2022-03-07,2,일반건축물,1
8000899,4427033022100500001,205.0,92.00,44.88,92.00,44.88,동물및식물관련시설,0,0,충청남도 당진시 대호지면 사성리 50-1,44270,33022,,NaN,2022-03-07,2,일반건축물,1
8000900,4427039032100180012,0.0,140.00,0.00,140.00,0.00,동물및식물관련시설,0,0,충청남도 당진시 송산면 동곡리 18-12,44270,39032,,NaN,2022-03-07,2,일반건축물,1
8000901,4427039032101560026,990.0,148.32,14.98,142.32,14.38,제1종근린생활시설,0,0,충청남도 당진시 송산면 동곡리 156-26,44270,39032,충청남도 당진시 송산면 동곡로 84-67,소매점,2022-03-07,2,일반건축물,1
8000902,4427025334103390004,0.0,108.90,0.00,108.90,0.00,공장,0,0,충청남도 당진시 송악읍 중흥리 339-4,44270,25334,,NaN,2022-03-07,2,일반건축물,1

In [7]:
result_df.to_csv('전처리_표제부_단일_pnucode.csv', index=False)

In [8]:
df1 = pd.read_csv('전처리_표제부_단일_pnucode.csv', dtype={'pnu_code': str})
df1

,pnu_code,plat_area,arch_area,bc_rat,tot_area,vl_rat,main_purps_cd_nm,hhld_cnt,tot_pkng_cnt,plat_plc,sigungu_cd,bjdong_cd,new_plat_plc,bld_nm,crtn_day,regstr_kind_cd,regstr_kind_cd_nm,main_bld_cnt
0,3020010400102710002,202.0,40.04,19.82,38.40,19.01,공동주택,2,2,대전광역시 유성구 용계동 271-2,30200,10400,대전광역시 유성구 용계로 101-18,NaN,2010-04-17,3,표제부,1
1,3020010400101650014,719.0,141.48,19.68,546.24,75.97,공동주택,19,13,대전광역시 유성구 용계동 165-14,30200,10400,대전광역시 유성구 용계로94번길 136-7,NaN,2010-04-17,3,표제부,1
2,2729011100108770001,191.8,112.83,58.83,193.80,101.04,공동주택,2,0,대구광역시 달서구 용산동 877-1,27290,11100,대구광역시 달서구 와룡로51길 64-20,NaN,2010-04-17,3,표제부,1
3,2717010200127150000,69.4,50.95,73.41,152.85,220.24,공동주택,2,0,대구광역시 서구 비산동 2715,27170,10200,대구광역시 서구 북비산로74길 35-2,NaN,2010-04-17,3,표제부,1
4,2811014700104310001,0.0,0.00,0.00,69.09,0.00,단독주택,0,0,인천광역시 중구 운서동 431-1,28110,14700,NaN,NaN,2009-03-17,2,일반건축물,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4924207,4427033021200300001,989.0,142.88,14.45,142.88,14.45,제2종근린생활시설,0,0,충청남도 당진시 대호지면 조금리 산 30-1,44270,33021,NaN,NaN,2022-03-07,2,일반건축물,1
4924208,4427033022100500001,205.0,92.00,44.88,92.00,44.88,동물및식물관련시설,0,0,충청남도 당진시 대호지면 사성리 50-1,44270,33022,NaN,NaN,2022-03-07,2,일반건축물,1
4924209,4427039032100180012,0.0,140.00,0.00,140.00,0.00,동물및식물관련시설,0,0,충청남도 당진시 송산면 동곡리 18-12,44270,39032,NaN,NaN,2022-03-07,2,일반건축물,1
4924210,4427039032101560026,990.0,148.32,14.98,142.32,14.38,제1종근린생활시설,0,0,충청남도 당진시 송산면 동곡리 156-26,44270,39032,충청남도 당진시 송산면 동곡로 84-67,소매점,2022-03-07,2,일반건축물,1
4924211,4427025334103390004,0.0,108.90,0.00,108.90,0.00,공장,0,0,충청남도 당진시 송악읍 중흥리 339-4,44270,25334,NaN,NaN,2022-03-07,2,일반건축물,1

In [ ]:
# 총괄표제부 전처리 진행
# 파일 경로 지정
file_path = 'files/dataset/원본데이터/표제부데이터셋/총괄표제부.txt'

field_mapping = {
    "대지면적": "plat_area",
    "건축면적": "arch_area",
    "건폐율": "bc_rat",
    "연면적": "tot_area",
    "용적률": "vl_rat",
    "주용도코드명": "main_purps_cd_nm",
    "생성일자": "crtn_day",
    "세대수": "hhld_cnt",
    "주건축물수": "main_bld_cnt",
    "총주차수": "tot_pkng_cnt",
    "대지위치": "plat_plc",
    "시군구코드": "sigungu_cd",
    "법정동코드": "bjdong_cd",
    "도로명대지위치": "new_plat_plc",
    "건물명": "bld_nm",
    '대장종류코드': 'regstr_kind_cd',
    '대장종류코드명': 'regstr_kind_cd_nm',
}

# 헤더 리스트 생성
headers = [
    "관리건축물대장PK",
    "대장구분코드",
    "대장구분코드명",
    "대장종류코드",
    "대장종류코드명",
    "신구대장구분코드",
    "신구대장구분코드명",
    "대지위치",
    "도로명대지위치",
    "건물명",
    "시군구코드",
    "법정동코드",
    "대지구분코드",
    "번",
    "지",
    "특수지명",
    "블록",
    "로트",
    "외필지수",
    "새주소도로코드",
    "새주소법정동코드",
    "새주소지상지하코드",
    "새주소본번",
    "새주소부번",
    "대지면적",
    "건축면적",
    "건폐율",
    "연면적",
    "용적률산정연면적",
    "용적률",
    "주용도코드",
    "주용도코드명",
    "기타용도",
    "세대수",
    "가구수",
    "주건축물수",
    "부속건축물수",
    "부속건축물면적",
    "총주차수",
    "옥내기계식대수",
    "옥내기계식면적",
    "옥외기계식대수",
    "옥외기계식면적",
    "옥내자주식대수",
    "옥내자주식면적",
    "옥외자주식대수",
    "옥외자주식면적",
    "허가일",
    "착공일",
    "사용승인일",
    "허가번호년",
    "허가번호기관코드",
    "허가번호기관코드명",
    "허가번호구분코드",
    "허가번호구분코드명",
    "호수",
    "에너지효율등급",
    "에너지절감율",
    "EPI점수",
    "친환경건축물등급",
    "친환경건축물인증점수",
    "지능형건축물등급",
    "지능형건축물인증점수",
    "생성일자"
]


# pnu 코드를 만드는 함수
def create_pnu(row):
    # 대장구분코드 조건에 따라 변환
    if row['대지구분코드'] == '0':
        plat_code = '1'
    elif row['대지구분코드'] == '1':
        plat_code = '2'
    else:
        return None

    # '번'과 '지'를 문자열로 강제 변환하고 zfill로 패딩 추가
    bun = str(int(row['번'])).zfill(4)
    ji = str(int(row['지'])).zfill(4)
    return f"{row['시군구코드']}{row['법정동코드']}{plat_code}{bun}{ji}"


# 데이터프레임으로 읽어오기
master_df = pd.read_csv(file_path, delimiter='|', encoding='cp949', names=headers,
                 dtype={'법정동코드': str, '시군구코드': str, '대지구분코드': str, '번': str, '지': str})

In [ ]:
# 'address' 열에서 '번지' 문자열 제거
master_df['대지위치'] = master_df['대지위치'].str.replace('번지', '', regex=False)

# pnu 코드 생성 전에 NaN 값이 있는 행을 제거
master_df.dropna(subset=['시군구코드', '법정동코드', '대지구분코드', '번', '지','주용도코드명'], inplace=True)

# 새로운 pnu 코드 컬럼 추가
master_df['pnu_code'] = master_df.apply(create_pnu, axis=1)

# 일반, 산이 아닌경우 None을 넣어 제거
master_df.dropna(subset=['pnu_code'], inplace=True)

# 데이터프레임 제거 컬럼 선정 후 제거
master_df = master_df[['pnu_code','대지면적', '건축면적', '건폐율', '연면적', '용적률', '주용도코드명', '생성일자', '대장종류코드', '대장종류코드명', '세대수', '주건축물수', '총주차수', '대지위치',
         '시군구코드', '법정동코드', '도로명대지위치', '건물명','가구수','호수','옥내기계식대수','옥외기계식대수','옥내자주식대수','옥외자주식대수']]

# 문자열을 포함하고 있는 열만 확인하여 앞뒤 공백 찍힌거 제거
for column in master_df.columns:
    if master_df[column].dtype == 'object':
        master_df[column] = master_df[column].str.strip()

# 날짜 열을 datetime 형식으로 변환
master_df['생성일자'] = pd.to_datetime(master_df['생성일자'], format='%Y%m%d')

# 각 pnu_code 그룹에서 생성일자의 최대값을 찾기
max_dates = master_df.groupby('pnu_code')['생성일자'].transform('max')

# 최대값과 일치하는 모든 행을 선택하기
master_df = master_df[master_df['생성일자'] == max_dates]

# 생성일자가 같아 2개이상이 반영된 pnu_code를 위해 중복 제거
master_df = master_df.drop_duplicates(subset=['pnu_code'], keep='first')

# 세대수가 0인 경우, 가구수 컬럼으로 먼저 대체
master_df['세대수'] = np.where(master_df['세대수'] == 0, master_df['가구수'], master_df['세대수'])

# 위에서 계산한 결과가 여전히 0이면, 호수 컬럼으로 대체
master_df['세대수'] = np.where(master_df['세대수'] == 0, master_df['호수'], master_df['세대수'])

# 주차 대수 컬럼들의 합을 총주차수 컬럼에 저장
master_df['총주차수'] = master_df['옥내기계식대수'] + master_df['옥외기계식대수'] + master_df['옥내자주식대수'] + master_df['옥외자주식대수']

# 계산 끝난 불필요한 컬럼 제거
master_df.drop(['가구수', '호수', '옥내기계식대수', '옥외기계식대수', '옥내자주식대수', '옥외자주식대수'], axis=1, inplace=True)

# 데이터프레임 컬럼명 영문으로 변경
master_df.rename(columns=field_mapping, inplace=True)

# 전처리된 데이터프레임 확인
master_df

In [ ]:
master_df.to_csv('files/dataset/건물정보/전처리_총괄표제부.csv', index=False)

In [10]:
df2 = pd.read_csv('files/dataset/건물정보/전처리_총괄표제부.csv', dtype={'pnu_code': str})
df2

,pnu_code,plat_area,arch_area,bc_rat,tot_area,vl_rat,main_purps_cd_nm,crtn_day,regstr_kind_cd,regstr_kind_cd_nm,hhld_cnt,main_bld_cnt,tot_pkng_cnt,plat_plc,sigungu_cd,bjdong_cd,new_plat_plc,bld_nm
0,5115034022101100026,9826.0,1317.60,13.41,1304.47,13.28,공장,2010-04-17,1,총괄표제부,0,3,0,강원특별자치도 강릉시 강동면 모전리 110-26,51150,34022,강원특별자치도 강릉시 강동면 동해대로 1869-26,NaN
1,5176036021100720001,0.0,179.91,35.98,270.55,54.11,단독주택,2010-04-17,1,총괄표제부,0,3,0,강원특별자치도 평창군 진부면 하진부리 72-1,51760,36021,강원특별자치도 평창군 진부면 영정게길 6-12,NaN
2,4315034027111620000,3245.0,695.80,21.44,695.80,21.44,공장,2010-04-17,1,총괄표제부,0,3,0,충청북도 제천시 덕산면 선고리 1162,43150,34027,충청북도 제천시 덕산면 약초로 281,NaN
3,4315034021106690001,625.0,178.43,28.55,235.27,37.64,제1종근린생활시설,2010-04-17,1,총괄표제부,0,2,0,충청북도 제천시 덕산면 도전리 669-1,43150,34021,충청북도 제천시 덕산면 도전로4길 23-8,NaN
4,4315034021103640007,1722.0,474.84,27.57,648.15,37.64,제1종근린생활시설,2010-04-17,1,총괄표제부,0,2,5,충청북도 제천시 덕산면 도전리 364-7,43150,34021,NaN,덕산면보건지소및소방차고
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586406,4427033021103590000,0.0,169.00,0.00,169.00,0.00,단독주택,2022-03-07,1,총괄표제부,3,3,0,충청남도 당진시 대호지면 조금리 359,44270,33021,NaN,NaN
586407,4427039025104310000,825.0,178.28,21.61,168.16,20.38,단독주택,2022-03-07,1,총괄표제부,1,2,0,충청남도 당진시 송산면 매곡리 431,44270,39025,충청남도 당진시 송산면 은곡길 68-1,유내영씨주택
586408,4427031021105260012,997.0,221.00,22.17,221.00,22.17,동물및식물관련시설,2022-03-07,1,총괄표제부,0,2,0,충청남도 당진시 고대면 용두리 526-12,44270,31021,NaN,NaN
586409,4427010500100010000,2114.0,775.03,36.66,1440.27,68.13,창고시설,2022-03-07,1,총괄표제부,0,2,0,충청남도 당진시 시곡동 1,44270,10500,NaN,NaN
586410,4427033027101090000,0.0,125.00,0.00,125.00,0.00,단독주택,2022-03-07,1,총괄표제부,2,2,0,충청남도 당진시 대호지면 마중리 109,44270,33027,충청남도 당진시 대호지면 새마실로 319-12,NaN

In [11]:
# 총괄표제부, 표제부 병합 전처리 진행
# df2에는 없는 pnu_code를 찾기
missing_pnu_codes = df1[~df1['pnu_code'].isin(df2['pnu_code'].unique())]

print("표제부에서 가져와야 할 데이터")
missing_pnu_codes

표제부에서 가져와야 할 데이터

,pnu_code,plat_area,arch_area,bc_rat,tot_area,vl_rat,main_purps_cd_nm,hhld_cnt,tot_pkng_cnt,plat_plc,sigungu_cd,bjdong_cd,new_plat_plc,bld_nm,crtn_day,regstr_kind_cd,regstr_kind_cd_nm,main_bld_cnt
0,3020010400102710002,202.0,40.04,19.82,38.40,19.01,공동주택,2,2,대전광역시 유성구 용계동 271-2,30200,10400,대전광역시 유성구 용계로 101-18,NaN,2010-04-17,3,표제부,1
1,3020010400101650014,719.0,141.48,19.68,546.24,75.97,공동주택,19,13,대전광역시 유성구 용계동 165-14,30200,10400,대전광역시 유성구 용계로94번길 136-7,NaN,2010-04-17,3,표제부,1
2,2729011100108770001,191.8,112.83,58.83,193.80,101.04,공동주택,2,0,대구광역시 달서구 용산동 877-1,27290,11100,대구광역시 달서구 와룡로51길 64-20,NaN,2010-04-17,3,표제부,1
3,2717010200127150000,69.4,50.95,73.41,152.85,220.24,공동주택,2,0,대구광역시 서구 비산동 2715,27170,10200,대구광역시 서구 북비산로74길 35-2,NaN,2010-04-17,3,표제부,1
4,2811014700104310001,0.0,0.00,0.00,69.09,0.00,단독주택,0,0,인천광역시 중구 운서동 431-1,28110,14700,NaN,NaN,2009-03-17,2,일반건축물,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4924207,4427033021200300001,989.0,142.88,14.45,142.88,14.45,제2종근린생활시설,0,0,충청남도 당진시 대호지면 조금리 산 30-1,44270,33021,NaN,NaN,2022-03-07,2,일반건축물,1
4924208,4427033022100500001,205.0,92.00,44.88,92.00,44.88,동물및식물관련시설,0,0,충청남도 당진시 대호지면 사성리 50-1,44270,33022,NaN,NaN,2022-03-07,2,일반건축물,1
4924209,4427039032100180012,0.0,140.00,0.00,140.00,0.00,동물및식물관련시설,0,0,충청남도 당진시 송산면 동곡리 18-12,44270,39032,NaN,NaN,2022-03-07,2,일반건축물,1
4924210,4427039032101560026,990.0,148.32,14.98,142.32,14.38,제1종근린생활시설,0,0,충청남도 당진시 송산면 동곡리 156-26,44270,39032,충청남도 당진시 송산면 동곡로 84-67,소매점,2022-03-07,2,일반건축물,1
4924211,4427025334103390004,0.0,108.90,0.00,108.90,0.00,공장,0,0,충청남도 당진시 송악읍 중흥리 339-4,44270,25334,NaN,NaN,2022-03-07,2,일반건축물,1

In [12]:
# missing_pnu_codes와 df2를 결합합니다
combined_df = pd.concat([df2, missing_pnu_codes], ignore_index=True)

# 새로운 데이터프레임을 출력
print("병합한 데이터")
combined_df

병합한 데이터

,pnu_code,plat_area,arch_area,bc_rat,tot_area,vl_rat,main_purps_cd_nm,crtn_day,regstr_kind_cd,regstr_kind_cd_nm,hhld_cnt,main_bld_cnt,tot_pkng_cnt,plat_plc,sigungu_cd,bjdong_cd,new_plat_plc,bld_nm
0,5115034022101100026,9826.0,1317.60,13.41,1304.47,13.28,공장,2010-04-17,1,총괄표제부,0,3,0,강원특별자치도 강릉시 강동면 모전리 110-26,51150,34022,강원특별자치도 강릉시 강동면 동해대로 1869-26,NaN
1,5176036021100720001,0.0,179.91,35.98,270.55,54.11,단독주택,2010-04-17,1,총괄표제부,0,3,0,강원특별자치도 평창군 진부면 하진부리 72-1,51760,36021,강원특별자치도 평창군 진부면 영정게길 6-12,NaN
2,4315034027111620000,3245.0,695.80,21.44,695.80,21.44,공장,2010-04-17,1,총괄표제부,0,3,0,충청북도 제천시 덕산면 선고리 1162,43150,34027,충청북도 제천시 덕산면 약초로 281,NaN
3,4315034021106690001,625.0,178.43,28.55,235.27,37.64,제1종근린생활시설,2010-04-17,1,총괄표제부,0,2,0,충청북도 제천시 덕산면 도전리 669-1,43150,34021,충청북도 제천시 덕산면 도전로4길 23-8,NaN
4,4315034021103640007,1722.0,474.84,27.57,648.15,37.64,제1종근린생활시설,2010-04-17,1,총괄표제부,0,2,5,충청북도 제천시 덕산면 도전리 364-7,43150,34021,NaN,덕산면보건지소및소방차고
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5500317,4427033021200300001,989.0,142.88,14.45,142.88,14.45,제2종근린생활시설,2022-03-07,2,일반건축물,0,1,0,충청남도 당진시 대호지면 조금리 산 30-1,44270,33021,NaN,NaN
5500318,4427033022100500001,205.0,92.00,44.88,92.00,44.88,동물및식물관련시설,2022-03-07,2,일반건축물,0,1,0,충청남도 당진시 대호지면 사성리 50-1,44270,33022,NaN,NaN
5500319,4427039032100180012,0.0,140.00,0.00,140.00,0.00,동물및식물관련시설,2022-03-07,2,일반건축물,0,1,0,충청남도 당진시 송산면 동곡리 18-12,44270,39032,NaN,NaN
5500320,4427039032101560026,990.0,148.32,14.98,142.32,14.38,제1종근린생활시설,2022-03-07,2,일반건축물,0,1,0,충청남도 당진시 송산면 동곡리 156-26,44270,39032,충청남도 당진시 송산면 동곡로 84-67,소매점
5500321,4427025334103390004,0.0,108.90,0.00,108.90,0.00,공장,2022-03-07,2,일반건축물,0,1,0,충청남도 당진시 송악읍 중흥리 339-4,44270,25334,NaN,NaN

In [4]:
combined_df.to_csv('files/dataset/건물정보/전처리_표제부_총괄표제부_병합.csv', index=False)

TypeError: read_csv() got an unexpected keyword argument 'index'

In [3]:
# 표제부+총괄표제부 병합파일 로드
combined_df = pd.read_csv('files/dataset/건물정보/전처리_표제부_총괄표제부_병합.csv')

combined_df

,pnu_code,plat_area,arch_area,bc_rat,tot_area,vl_rat,main_purps_cd_nm,crtn_day,regstr_kind_cd,regstr_kind_cd_nm,hhld_cnt,main_bld_cnt,tot_pkng_cnt,plat_plc,sigungu_cd,bjdong_cd,new_plat_plc,bld_nm
0,5115034022101100026,9826.0,1317.60,13.41,1304.47,13.28,공장,2010-04-17,1,총괄표제부,0,3,0,강원특별자치도 강릉시 강동면 모전리 110-26,51150,34022,강원특별자치도 강릉시 강동면 동해대로 1869-26,NaN
1,5176036021100720001,0.0,179.91,35.98,270.55,54.11,단독주택,2010-04-17,1,총괄표제부,0,3,0,강원특별자치도 평창군 진부면 하진부리 72-1,51760,36021,강원특별자치도 평창군 진부면 영정게길 6-12,NaN
2,4315034027111620000,3245.0,695.80,21.44,695.80,21.44,공장,2010-04-17,1,총괄표제부,0,3,0,충청북도 제천시 덕산면 선고리 1162,43150,34027,충청북도 제천시 덕산면 약초로 281,NaN
3,4315034021106690001,625.0,178.43,28.55,235.27,37.64,제1종근린생활시설,2010-04-17,1,총괄표제부,0,2,0,충청북도 제천시 덕산면 도전리 669-1,43150,34021,충청북도 제천시 덕산면 도전로4길 23-8,NaN
4,4315034021103640007,1722.0,474.84,27.57,648.15,37.64,제1종근린생활시설,2010-04-17,1,총괄표제부,0,2,5,충청북도 제천시 덕산면 도전리 364-7,43150,34021,NaN,덕산면보건지소및소방차고
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5500317,4427033021200300001,989.0,142.88,14.45,142.88,14.45,제2종근린생활시설,2022-03-07,2,일반건축물,0,1,0,충청남도 당진시 대호지면 조금리 산 30-1,44270,33021,NaN,NaN
5500318,4427033022100500001,205.0,92.00,44.88,92.00,44.88,동물및식물관련시설,2022-03-07,2,일반건축물,0,1,0,충청남도 당진시 대호지면 사성리 50-1,44270,33022,NaN,NaN
5500319,4427039032100180012,0.0,140.00,0.00,140.00,0.00,동물및식물관련시설,2022-03-07,2,일반건축물,0,1,0,충청남도 당진시 송산면 동곡리 18-12,44270,39032,NaN,NaN
5500320,4427039032101560026,990.0,148.32,14.98,142.32,14.38,제1종근린생활시설,2022-03-07,2,일반건축물,0,1,0,충청남도 당진시 송산면 동곡리 156-26,44270,39032,충청남도 당진시 송산면 동곡로 84-67,소매점
5500321,4427025334103390004,0.0,108.90,0.00,108.90,0.00,공장,2022-03-07,2,일반건축물,0,1,0,충청남도 당진시 송악읍 중흥리 339-4,44270,25334,NaN,NaN

In [9]:
# 집품 데이터 업로드
star_score_df = pd.read_csv('files/dataset/(SSAFY 기업 연계 프로젝트) Nextground 건물 별점 정보 지역수정.csv')
star_score_df.drop(columns=['new_plat_plc'],errors='raise', inplace=True)
star_score_df

          id                 plat_plc  avg_score   bld_type
0          1        서울특별시 송파구 석촌동 1-6   3.487179  OFFICETEL
1          2        광주광역시 북구 용봉동 1468   3.600000  APARTMENT
2          3  경기도 고양시 일산동구 중산동 1601-2   4.250000      HOUSE
3          4        서울특별시 구로구 천왕동 280   4.125000  APARTMENT
4          5  경기도 고양시 일산동구 중산동 1585-5   4.000000      HOUSE
...      ...                      ...        ...        ...
24995  24996       서울특별시 구로구 구로동 28-5   1.500000      HOUSE
24996  24997     서울특별시 영등포구 신길동 449-3   2.000000      HOUSE
24997  24998    서울특별시 관악구 신림동 1583-11   1.500000      HOUSE
24998  24999      서울특별시 강동구 암사동 431-8   2.500000      HOUSE
24999  25000    서울특별시 강서구 화곡동 1075-15   2.500000  OFFICETEL

[25000 rows x 4 columns]

In [10]:
# 전처리된 데이터프레임 머지 확인
merge_df = pd.merge(star_score_df, combined_df, on='plat_plc', how='left')
merge_df

,id,plat_plc,avg_score,bld_type,pnu_code,plat_area,arch_area,bc_rat,tot_area,vl_rat,...,crtn_day,regstr_kind_cd,regstr_kind_cd_nm,hhld_cnt,main_bld_cnt,tot_pkng_cnt,sigungu_cd,bjdong_cd,new_plat_plc,bld_nm
0,1,서울특별시 송파구 석촌동 1-6,3.487179,OFFICETEL,1.171011e+18,693.70,414.5700,59.760000,4398.4800,475.42,...,2017-12-05,3.0,표제부,63.0,1.0,41.0,11710.0,10500.0,서울특별시 송파구 송파대로49길 64,레이크캐슬
1,2,광주광역시 북구 용봉동 1468,3.600000,APARTMENT,2.917011e+18,27677.20,4825.5706,17.435183,96645.0666,273.24,...,2021-07-07,1.0,총괄표제부,642.0,8.0,797.0,29170.0,10700.0,광주광역시 북구 용주로30번길 60,용봉동 한화 꿈에그린 아파트
2,3,경기도 고양시 일산동구 중산동 1601-2,4.250000,HOUSE,4.128510e+18,211.00,124.8500,59.170000,440.0900,149.40,...,2019-04-05,2.0,일반건축물,16.0,1.0,3.0,41285.0,10200.0,경기도 고양시 일산동구 중산로157번길 22,NaN
3,4,서울특별시 구로구 천왕동 280,4.125000,APARTMENT,1.153011e+18,27467.50,6252.6000,22.760000,74539.6800,170.76,...,2023-09-20,1.0,총괄표제부,571.0,12.0,695.0,11530.0,11100.0,NaN,천왕연지타운1단지
4,5,경기도 고양시 일산동구 중산동 1585-5,4.000000,HOUSE,4.128510e+18,200.90,120.3800,59.920000,328.4900,163.51,...,2022-03-03,2.0,일반건축물,8.0,1.0,2.0,41285.0,10200.0,경기도 고양시 일산동구 탄중로417번길 9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,24996,서울특별시 구로구 구로동 28-5,1.500000,HOUSE,1.153010e+18,0.00,65.4900,0.000000,214.3000,0.00,...,2023-12-04,2.0,일반건축물,7.0,1.0,0.0,11530.0,10200.0,서울특별시 구로구 새말로18길 36-7,구로동 28-5 단독주택 (박명숙)
24996,24997,서울특별시 영등포구 신길동 449-3,2.000000,HOUSE,1.156013e+18,366.90,190.0600,51.800000,1260.1000,292.12,...,2018-07-10,3.0,표제부,15.0,1.0,12.0,11560.0,13200.0,서울특별시 영등포구 영등포로86길 4,소소방
24997,24998,서울특별시 관악구 신림동 1583-11,1.500000,HOUSE,1.162010e+18,78.39,44.9100,57.290000,173.9500,166.14,...,2018-09-15,2.0,일반건축물,1.0,1.0,1.0,11620.0,10200.0,서울특별시 관악구 남부순환로166길 47,NaN
24998,24999,서울특별시 강동구 암사동 431-8,2.500000,HOUSE,1.174011e+18,161.00,91.3200,56.720000,246.7900,153.29,...,2019-06-21,2.0,일반건축물,8.0,1.0,4.0,11740.0,10700.0,서울특별시 강동구 암사길 83-20,NaN
24999,25000,서울특별시 강서구 화곡동 1075-15,2.500000,OFFICETEL,1.150010e+18,205.00,118.1500,57.630000,603.4000,294.34,...,2023-11-15,3.0,표제부,0.0,1.0,6.0,11500.0,10300.0,서울특별시 강서구 강서로 159-4,두선빌 오피스텔

In [11]:
merge_df.to_csv("files/dataset/check_data_240513.csv", index=False)

In [19]:
# 공시지가 맵핑
df_gongciziga = pd.read_csv('files/dataset/건물정보/전처리_개별공시지가.csv')
df_gongciziga

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_7124\2195089827.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_gongciziga = pd.read_csv('dataset/전처리_개별공시지가.csv')

,pnu_code,plat_plc,official_price,announced_date,base_date
0,1111010100100120009,서울특별시 종로구 청운동 12-9,5348000,2023-07-01,2024-01-20
1,1111010100101000003,서울특별시 종로구 청운동 100-3,4503000,2023-07-01,2024-01-20
2,1111010100101000007,서울특별시 종로구 청운동 100-7,4695000,2023-07-01,2024-01-20
3,1111010200100020049,서울특별시 종로구 신교동 2-49,3122000,2023-07-01,2024-01-20
4,1111011000102450006,서울특별시 종로구 누하동 245-6,8712000,2023-07-01,2024-01-20
...,...,...,...,...,...
34228938,5280042028201300000,전북특별자치도 부안군 위도면 하왕등리 130,1270,2023-01-01,2024-01-20
34228939,5280042028201310000,전북특별자치도 부안군 위도면 하왕등리 131,1270,2023-01-01,2024-01-20
34228940,5280042028201320000,전북특별자치도 부안군 위도면 하왕등리 132,1250,2023-01-01,2024-01-20
34228941,5280042028201330000,전북특별자치도 부안군 위도면 하왕등리 133,1250,2023-01-01,2024-01-20
34228942,5280042028201340000,전북특별자치도 부안군 위도면 하왕등리 134,5120,2023-01-01,2024-01-20

In [20]:
merge_df_plus_gongciziga = pd.merge(merge_df, df_gongciziga,on='plat_plc',how='left')
merge_df_plus_gongciziga

,id,new_plat_plc_x,plat_plc,avg_score,bld_type,pnu_code_x,plat_area,arch_area,bc_rat,tot_area,...,main_bld_cnt,tot_pkng_cnt,sigungu_cd,bjdong_cd,new_plat_plc_y,bld_nm,pnu_code_y,official_price,announced_date,base_date
0,1,서울특별시 송파구 송파대로49길 64,서울특별시 송파구 석촌동 1-6,3.487179,OFFICETEL,1.171011e+18,693.70,414.5700,59.760000,4398.4800,...,1.0,41.0,11710.0,10500.0,서울특별시 송파구 송파대로49길 64,레이크캐슬,1171010500100010006,11930000.0,2023-01-01,2024-01-20
1,2,광주광역시 북구 용주로30번길 60,광주광역시 북구 용봉동 1468,3.600000,APARTMENT,2.917011e+18,27677.20,4825.5706,17.435183,96645.0666,...,8.0,797.0,29170.0,10700.0,광주광역시 북구 용주로30번길 60,용봉동 한화 꿈에그린 아파트,2917010700114680000,1020000.0,2023-01-01,2024-01-20
2,3,경기도 고양시 일산동구 중산로157번길 22,경기도 고양시 일산동구 중산동 1601-2,4.250000,HOUSE,4.128510e+18,211.00,124.8500,59.170000,440.0900,...,1.0,3.0,41285.0,10200.0,경기도 고양시 일산동구 중산로157번길 22,NaN,4128510200116010002,1192000.0,2023-01-01,2024-01-20
3,4,서울특별시 구로구 오류로 30,서울특별시 구로구 천왕동 280,4.125000,APARTMENT,1.153011e+18,27467.50,6252.6000,22.760000,74539.6800,...,12.0,695.0,11530.0,11100.0,NaN,천왕연지타운1단지,1153011100102800000,3661000.0,2023-07-01,2024-01-20
4,5,경기도 고양시 일산동구 탄중로417번길 9,경기도 고양시 일산동구 중산동 1585-5,4.000000,HOUSE,4.128510e+18,200.90,120.3800,59.920000,328.4900,...,1.0,2.0,41285.0,10200.0,경기도 고양시 일산동구 탄중로417번길 9,NaN,4128510200115850005,1617000.0,2023-01-01,2024-01-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,24996,서울특별시 구로구 새말로18길 36-7,서울특별시 구로구 구로동 28-5,1.500000,HOUSE,1.153010e+18,0.00,65.4900,0.000000,214.3000,...,1.0,0.0,11530.0,10200.0,서울특별시 구로구 새말로18길 36-7,구로동 28-5 단독주택 (박명숙),1153010200100280005,4707000.0,2023-01-01,2024-01-20
24996,24997,서울특별시 영등포구 영등포로86길 4,서울특별시 영등포구 신길동 449-3,2.000000,HOUSE,1.156013e+18,366.90,190.0600,51.800000,1260.1000,...,1.0,12.0,11560.0,13200.0,서울특별시 영등포구 영등포로86길 4,소소방,1156013200104490003,5478000.0,2023-01-01,2024-01-20
24997,24998,서울특별시 관악구 남부순환로166길 47,서울특별시 관악구 신림동 1583-11,1.500000,HOUSE,1.162010e+18,78.39,44.9100,57.290000,173.9500,...,1.0,1.0,11620.0,10200.0,서울특별시 관악구 남부순환로166길 47,NaN,1162010200115830011,4033000.0,2023-01-01,2024-01-20
24998,24999,서울특별시 강동구 암사길 83-20,서울특별시 강동구 암사동 431-8,2.500000,HOUSE,1.174011e+18,161.00,91.3200,56.720000,246.7900,...,1.0,4.0,11740.0,10700.0,서울특별시 강동구 암사길 83-20,NaN,1174010700104310008,3992000.0,2023-01-01,2024-01-20
24999,25000,서울특별시 강서구 강서로 159-4,서울특별시 강서구 화곡동 1075-15,2.500000,OFFICETEL,1.150010e+18,205.00,118.1500,57.630000,603.4000,...,1.0,6.0,11500.0,10300.0,서울특별시 강서구 강서로 159-4,두선빌 오피스텔,1150010300110750015,6741000.0,2023-01-01,2024-01-20

In [21]:
# 공시지가까지 엎은 데이터셋 저장 -> 인프라 정보 엎어서 후 전처리 예정
merge_df_plus_gongciziga[['plat_plc','avg_score','bld_type','plat_area','arch_area','bc_rat','tot_area','vl_rat','hhld_cnt','main_bld_cnt','tot_pkng_cnt','official_price']].to_csv('dataset/check_data_240511.csv',index=False)

In [4]:
merge_df_plus_gongciziga = pd.read_csv('files/dataset/건물정보/dataset_with_building_info.csv')
merge_df_plus_gongciziga

,plat_plc,avg_score,bld_type,plat_area,arch_area,bc_rat,tot_area,vl_rat,hhld_cnt,main_bld_cnt,tot_pkng_cnt,official_price
0,서울특별시 송파구 석촌동 1-6,3.487179,OFFICETEL,693.7,414.5700,59.760000,4398.4800,475.42,63.0,1.0,41.0,11930000.0
1,광주광역시 북구 용봉동 1468,3.600000,APARTMENT,27677.2,4825.5706,17.435183,96645.0666,273.24,642.0,8.0,797.0,1020000.0
2,경기도 고양시 일산동구 중산동 1601-2,4.250000,HOUSE,211.0,124.8500,59.170000,440.0900,149.40,16.0,1.0,3.0,1192000.0
3,서울특별시 구로구 천왕동 280,4.125000,APARTMENT,27467.5,6252.6000,22.760000,74539.6800,170.76,571.0,12.0,695.0,3661000.0
4,경기도 고양시 일산동구 중산동 1585-5,4.000000,HOUSE,200.9,120.3800,59.920000,328.4900,163.51,8.0,1.0,2.0,1617000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
19995,서울특별시 광진구 군자동 473-21,3.535714,OFFICETEL,784.7,461.7400,58.840000,5821.0600,637.08,190.0,1.0,103.0,11650000.0
19996,서울특별시 영등포구 여의도동 11-1,2.166667,APARTMENT,0.0,833.0600,0.000000,12686.9000,0.00,190.0,1.0,0.0,12300000.0
19997,서울특별시 영등포구 여의도동 21-1,3.250000,APARTMENT,0.0,2742.8200,0.000000,34832.3500,0.00,192.0,2.0,0.0,14900000.0
19998,서울특별시 영등포구 당산동 121-61,4.190476,HOUSE,1490.0,783.0300,52.550000,13018.6600,646.69,314.0,1.0,161.0,5394000.0
19999,서울특별시 은평구 응암동 96-18,3.000000,APARTMENT,3087.7,1831.2900,59.300000,26426.4530,568.66,134.0,1.0,211.0,5990000.0